from dexy.plugin import Command
import web
from middleware import StaticMiddleware

class ViewerCommand(Command):
    """
    Starts a web.py application which lets you preview the snippets generated
    by your previous dexy run.
    """
    aliases = ['viewer']
    NAMESPACE = 'viewer'

def viewer_command(
        port=8090 # Port on which to run the viewer
        ):
    """
    Starts a web.py application which lets you preview the snippets generated by your previous dexy run.
    """
    import app as viewer
    func = viewer.app.wsgifunc()
    server_address =("0.0.0.0", port)

    func = StaticMiddleware(func)
    func = web.httpserver.LogMiddleware(func)

    server = web.httpserver.WSGIServer(server_address, func)

    print "http://%s:%d/" % server_address
    print "Type ctrl+c to stop the server."
    try:
        server.start()
    except KeyboardInterrupt:
        server.stop()

def ping_command():
    print "pong"
